name: project_environment
dependencies:
  # The python interpreter version.

  # Currently Azure ML Workbench only supports 3.5.2 and later.

- python=3.6.2
  # Required by azureml-defaults, installed separately through Conda to

  # get a prebuilt version and not require build tools for the install.

- psutil=5.3

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-sdk[notebooks]
  - pynacl==1.2.1
  - scipy==1.0.0
  - scikit-learn==0.19.1
  - pandas==0.23.1
  - numpy==1.14.5